Fname=input('enter your first name: ')
Sname=input('enter your second name: ')
Tname=input('enter your third name: ')
full_name=input('enter your family name: ')
print(Fname,"-",Sname,"-",Tname,"-",full_name)
